export const payload = {
  navigation:{
    populate: {
      logo:{
        fields:['title'],
        populate:{
          image:{
            fields:['url']
          }
        }
      },
      types:{
        fields:['title','value','order']
      },
      social_medias:{
        populate:{
          image:{
            fields:'url'
          },
          fields:['title','value','link']
        }
      },
      fields:'locale',
      locale:"ckb"
    }
  },
  footer:{
    populate:{
      logo:{
        populate:{
          image:{
            fields:['url']
          }
        }
      },
      language:{
        fields:['title']
      },
      social_media:{
        fields:['title'],
        populate:{
          social_medias:{
            fields:['id','title','value','link'],
            populate:{
              image:{
                fields:['url']
              }
            }
          }
        }
      },
      channel:{
        fields:['title'],
        populate:{
          channels:{
            fields:['link','title'],
            populate:{
              image:{
                fields:['url']
              }
            }
          }
        }
      },
      copy_right:{
        fields:['title','link']
      },
      terms:{
        fields:['title']
      },
      types:{
        fields:['title','value','id']
      },
    },
    fields:['locale','body'],
    locale:"ckb"
  },
  homeHero:{
    pagination:{
      limit:5
    },
    sort:"date:desc",
    fields:['locale','title','body','video_link','trailer_link','date','slug','length','ua_certificate'],
    populate:{
      thumbnail:{
        fields:['url']
      },
      type:{
        fields:['id']
      },
      banner:{
        populate:{
          landscape:{
            fields:['url']
          },
          portrait:{
            fields:['url']
          }
        }
      },
      genres:{
        fields:['title']
      },
    },
    locale:"ckb"
  },
  homeHeroSpecial:{
    populate:{
      videos:{
        fields:["title","body","video_link","trailer_link","date","slug","length","ua_certificate"],
        populate:{
          banner:{
            populate:{
              landscape:{
                fields:['url']
              },
              portrait:{
                fields:['url']
              }
            }
          },
          video:{
            fields:['url']
          },
          trailer:{
            fields:['url']
          },
          genres:{
            fields:['title']
          },
          type:{
            fields:['id']
          }
        }
      },
      series:{
        fields:['title','date','slug','ua_certificate'],
        populate:{
          banner:{
            populate:{
              landscape:{
                fields:['url'] 
              },
              portrait:{
                fields:['url'] 
              }
            }
          },
          genres:{
            fields:['title']
          },
          types:{
            fields:['id']
          }
        }
      }
    }
  }
};